---
driver:
  name: vagrant
  provider: hyperv

provisioner:
  name: chef_infra

platforms:
  - name: windows-2019
  - name: windows-2016

suites:
  - name: default
    run_list:
      - recipe[snmp::default]
    verifier:
      name: inspec

verifier:
  inspec_tests:
    - test/integration/default/inspec
