# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rake
    - name: Check Chef Cookbook Metadata
      # You may pin to the exact commit or the version.
      # uses: damacus/check-chef-metadata-action@210895a699826f25d1dc3a71ab862c8b0f191e4a
      uses: damacus/check-chef-metadata-action@0.0.2
      with:
        # Github token
        token: 
        # Maintainer email
        maintainer_email: # optional, default is help@sous-chefs.org
        # Desired name of the maintainer
        maintainer: # optional, default is Sous Chefs
        # A SPDX licence
        license: # optional, default is Apache-2.0
