name: kitchen
on: [push, pull_request]
jobs:
  kitchen:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Vagrant
        uses: actions/setup-vagrant@v2
      - name: Install VirtualBox
        run: |
          sudo apt-get install virtualbox
          sudo apt-get install virtualbox—ext–pack
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Kitchen Converge
        uses: actionshub/test-kitchen@1.0.2
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.yml
          TERM: xterm-256color
      - name: Kitchen Verify
        uses: actionshub/test-kitchen@1.0.2
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.yml
          TERM: xterm-256color
