name: kitchen
on: [push, pull_request]
jobs:
  kitchen:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Vagrant
        run: | 
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt update && sudo apt install -y vagrant
          vagrant autocomplete install
        cache:
          key: vagrant-install
          restore-keys:
            - vagrant-install-v1
            - vagrant-install-v2
          paths:
            - /usr/bin/vagrant
      - name: Install VirtualBox
        run: |
          sudo apt-get install virtualbox
        cache:
          key: virtualbox-install
          restore-keys:
            - virtualbox-install-v1
            - virtualbox-install-v2
          paths:
            - /usr/bin/vboxmanage
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Kitchen Converge
        uses: actionshub/test-kitchen@1.0.2
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.yml
          TERM: xterm-256color
      - name: Kitchen Verify
        uses: actionshub/test-kitchen@1.0.2
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.yml
          TERM: xterm-256color
